#!/bin/bash
clear
echo " Starting Box64Droid (virgl version) installation..." & sleep 3
echo ""
echo " Box64Droid creates /sdcard/Box64Droid folder to store configuration files. To create this folder, it is necessary to have storage permissions, click on allow to proceed." & sleep 5 &>/dev/null
termux-setup-storage & sleep 3 &>/dev/null
echo ""
echo " Updating packages..."
apt-get update &>/dev/null
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade &>/dev/null
echo ""
echo " Installing x11-repo..."
echo ""
pkg install x11-repo -y &>/dev/null
echo " x11-repo installed"
echo ""
echo " Installing required packages..."
pkg install pulseaudio wget xkeyboard-config virglrenderer-android proot-distro termux-x11-nightly termux-am -y &>/dev/null
echo ""
echo " Checking for older Box64Droid versions and removing them if any..."
echo ""
proot-distro remove ubuntu-box64droid &>/dev/null
if [ -d /sdcard/Box64Droid ]
then
  rm -r /sdcard/Box64Droid &>/dev/null
fi
echo " Downloading Box64Droid rootfs..."
echo ""
if [ ! -d /data/data/com.termux/files/usr/var/lib/proot-distro ]
then
    mkdir /data/data/com.termux/files/usr/var/lib/proot-distro
    mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
    mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu
fi
wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/stable/box64droid-rootfs-virgl.tar.xz
echo ""
echo " Installing Box64Droid rootfs, please wait..."
proot-distro restore box64droid-rootfs-virgl.tar.xz &>/dev/null
echo ""
echo " Downloading Box64Droid starting scripts..."
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/virgl/box64droid &>/dev/null
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/non-root/start-box64droid &>/dev/null
chmod +x start-box64droid
chmod +x box64droid
mv box64droid $PREFIX/bin/
mv start-box64droid $PREFIX/bin/
echo ""
echo " Scripts downloaded"
echo ""
echo " Removing the installation waste..."
rm box64droid-rootfs-virgl.tar.xz install virgl
clear
echo ""
echo " Install finished. To start Box64Droid run 'box64droid --start', to see more arguments run 'box64droid --help'"
echo ""
echo " And if everything goes as planned, Wine and 7-Zip file manager will start."
echo ""
