#!/bin/bash
clear
echo " Starting Box64Droid (root version) installation..." & sleep 3
echo ""
echo " Box64Droid creates /sdcard/Box64Droid folder to store configuration files. To create this folder, it is necessary to have storage permissions, click on allow to proceed." & sleep 5 &>/dev/null
termux-setup-storage & sleep 3 &>/dev/null
echo ""
echo " Updating packages..."
apt-get update &>/dev/null
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade &>/dev/null
echo ""
echo " Installing x11-repo..."
echo ""
pkg install x11-repo -y &>/dev/null
echo " x11-repo installed"
echo ""
echo " Installing required packages..."
pkg install pulseaudio wget tsu xkeyboard-config termux-x11-nightly termux-am -y &>/dev/null
echo ""
echo " Checking for older Box64Droid versions and removing them if any..."
echo ""
if sudo [ -d /data/data/com.termux/files/home/ubuntu ]
then
  if [ -c ~/ubuntu/dev/urandom ]
  then
    echo "/dev not umounted correctly! Reboot device and run install script again"
    exit
  else
    sudo rm -r ~/ubuntu &>/dev/null
  fi
fi
if [ -d /sdcard/Box64Droid ]
then
  rm -r /sdcard/Box64Droid &>/dev/null
fi
echo " Downloading Box64Droid rootfs..."
echo ""
wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/stable/box64droid-rootfs-chroot.tar.xz
echo ""
echo " Installing Box64Droid rootfs, please wait..."
sudo mkdir ~/ubuntu
sudo tar -xJf box64droid-rootfs-chroot.tar.xz -C ~/ubuntu &>/dev/null
echo ""
echo " Downloading Box64Droid starting scripts..."
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/root/box64droid &>/dev/null
chmod +x box64droid
mv box64droid $PREFIX/bin/
echo ""
echo " Scripts downloaded"
echo ""
echo " Removing the installation waste..."
rm box64droid-rootfs-chroot.tar.xz install root
clear
echo ""
echo " Install finished. To start Box64Droid run 'box64droid --start', to see more arguments run 'box64droid --help'"
echo ""
echo " And if everything goes as planned, Wine and 7-Zip file manager will start."
echo ""
