#!/bin/bash
if [ $# -eq 0 ]
then
        echo "Empty argument, use --help to see available arguments"
elif [ $1 = "--start" ]
then
	unset LD_PRELOAD
	export ROOTFSPATH=~/ubuntu
	sudo mount -o remount,dev,suid /data
	sudo mount proc -t proc $ROOTFSPATH/proc
	sudo mount sys -t sysfs $ROOTFSPATH/sys
	sudo mount --bind /dev $ROOTFSPATH/dev
	sudo mount --bind /dev/pts $ROOTFSPATH/dev/pts
	sudo mount --bind /sdcard $ROOTFSPATH/sdcard
        echo "Starting Termux-x11..."
        termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
        echo ""
        echo -e "Termux-x11 started"
	sudo mount --bind $PREFIX/tmp/.X11-unix $ROOTFSPATH/tmp/.X11-unix
	echo ""
	echo "Starting Box64Droid..."
        echo ""
	sudo chroot $ROOTFSPATH /bin/su -
	sudo umount $ROOTFSPATH/proc
	sudo umount $ROOTFSPATH/sys
	sudo umount $ROOTFSPATH/dev/pts
	sudo umount $ROOTFSPATH/dev
	sudo umount $ROOTFSPATH/sdcard
	sudo umount $ROOTFSPATH/tmp/.X11-unix
	pkill -f "app_process / com.termux.x11"
elif [ $1 = "--update" ]
then
	cd ~/
        curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install
elif [ $1 = "--uninstall" ]
then
        echo "Uninstalling Box64Droid..."
        sudo rm -r ~/ubuntu
        rm $PREFIX/bin/box64droid
	echo "Done!"
elif [ $1 = "--version" ]
then
        echo "06.06.23 (beta)"
elif [ $1 = "--help" ]
then
        echo "Box64Droid (Root version) - preconfigured Ubuntu 22.04 rootfs with Box64, Box86, Wine Proton, DXVK and Adreno GPU drivers for Android"
        echo "Usage: box64droid {argument}"
 	echo "Available arguments:"
        echo "--start - start Box64Droid"
        echo "--update - update Box64Droid (all data in rootfs will be clear)"
        echo "--uninstall - uninstall Box64Droid (all data in rootfs will be clear)"
        echo "--version - show current version of Box64Droid"
        echo "--help - see available arguments"
else
        echo "Invalid argument, use --help to see available arguments"
fi
