#!/bin/bash
clear
echo "Select the needed Box64Droid version to install:"
echo "1) Non-root version (Adreno 610-740, Android 12+)."
echo "2) Root version (Adreno 610-740, Android 10+)."
echo "3) VirGL version (For other GPUs, non-root phones, Android 12+)."
echo "4) Native version (Adreno 610-740, testing version, thanks JeezDisReez for his hard works)."
echo "5) Cancel the Box64Droid installation."
echo ""
read version
if [ -z $version ]
then
    echo "Empty version! Re-run installation script and choose correct version"
    rm install
    exit
elif [ $version = 1 ]
then
    curl -o non-root https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/non-root/install && chmod +x non-root && ./non-root
elif [ $version = 2 ]
then
    curl -o root https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/root/install && chmod +x root && ./root
elif [ $version = 3 ]
then
    curl -o virgl https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/virgl/install && chmod +x virgl && ./virgl
elif [ $version = 4 ]
then
    curl -o native https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/native/install && chmod +x native && ./native
elif [ $version = 5 ]
then
    rm install
    exit
else
    echo "Wrong version! Re-run installation script and choose correct version"
    rm install
    exit
fi
