#!/bin/bash
clear
echo "Select need Box64Droid version to install:"
echo "1) Non-root version"
echo "2) Root version"
echo "3) VirGL version"
echo "4) Cancel Box64Droid installation"
echo ""
read version
if [ $version = 1 ] || [ $version = 2 ] || [ $version = 3 ]
then
	&>/dev/null
elif [ $version = 4 ]
then
	clear
	exit
else
	clear
	echo "Invalid version, rerun installation script"
	rm -rf install &>/dev/null
	exit
fi
clear
echo " Starting Box64Droid installation..." & sleep 3
echo " Box64Droid creates a folder called "Box64Droid" at the internal storage to store configuration files. For Termux to create this folder, it is necessary to have storage permissions, click on allow to proceed." & sleep 5 &>/dev/null	
termux-setup-storage & sleep 3 &>/dev/null
pkg update -y
echo ""
echo " Installing x11-repo..."
echo ""
pkg install x11-repo -y &>/dev/null
echo " x11-repo installed"
echo ""
echo " Installing need packages..."
if [ $version = 1 ]
then
       pkg install pulseaudio wget xkeyboard-config proot-distro -y &>/dev/null 
elif [ $version = 3 ]
then
       pkg install pulseaudio wget xkeyboard-config virglrenderer-android proot-distro -y &>/dev/null 
else
       pkg install pulseaudio wget tsu xkeyboard-config -y &>/dev/null
fi
echo ""
echo " Downloading and installing the Termux-x11 package..."
echo ""
wget https://github.com/Ilya114/Box64Droid/raw/main/apps/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
echo " Termux-x11 installed"
echo ""
echo " Checking for older Box64Droid and removing them if any" 
echo ""
if [ -f $PREFIX/bin/box64droid ]
then
	rm $PREFIX/bin/box64droid &>/dev/null
else
	&>/dev/null
fi
if [ -d /sdcard/Box64Droid ]
then
	rm -r /sdcard/Box64Droid &>/dev/null
else
	&>/dev/null
fi
if [ $version = 1 ] || [ $version = 3 ]
then
	proot-distro remove ubuntu &>/dev/null
else
	sudo rm -r ~/ubuntu &>/dev/null
fi
echo " Downloading preconfigured rootfs..."
echo ""
if [ $version = 1 ]
then
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/ &>/dev/null
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ &>/dev/null
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu &>/dev/null
	wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/beta/box64droid-rootfs-beta.tar.xz 
elif [ $version = 2 ]
then
	wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/chroot/box64droid-rootfs-beta-chroot.tar.xz
else
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/ &>/dev/null
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ &>/dev/null
	mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu &>/dev/null
	wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/virgl/box64droid-rootfs-beta-virgl.tar.xz
fi 
echo ""
echo " Installing rootfs, please wait..."
if [ $version = 1 ]
then
	proot-distro restore box64droid-rootfs-beta.tar.xz &>/dev/null
elif [ $version = 2 ]
then
	sudo mkdir ~/ubuntu
	sudo tar -xJf box64droid-rootfs-beta-chroot.tar.xz -C ~/ubuntu &>/dev/null  
else
	proot-distro restore box64droid-rootfs-beta-virgl.tar.xz &>/dev/null
fi
echo ""
echo " Rootfs installed"
echo ""
echo " Downloading Box64Droid starting script..."
if [ $version = 1 ]
then
	wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/box64droid &>/dev/null
	chmod +x box64droid &>/dev/null
	mv box64droid $PREFIX/bin/box64droid &>/dev/null
elif [ $version = 2 ]
then
	wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/box64droid-root &>/dev/null
	chmod +x box64droid-root &>/dev/null
	mv box64droid-root $PREFIX/bin/box64droid &>/dev/null
else
	wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/box64droid-virgl &>/dev/null
	chmod +x box64droid-virgl &>/dev/null
	mv box64droid-virgl $PREFIX/bin/box64droid &>/dev/null
fi
echo ""
echo " Script installed"
echo ""
echo " Removing installation waste..."
rm -rf box64droid-rootfs-beta*.tar.xz &>/dev/null
rm -rf install &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb &>/dev/null
clear
echo ""
echo " Install finished. To start Box64Droid type 'box64droid --start', to see more arguments type 'box64droid --help'"
echo ""
echo " And if everything goes as planned, the Wine environment will start and soon after TFM will open, that's it."
echo ""
