#!/bin/bash

echo "Starting Termux-x11..."
Xvfb :0 -ac &>/dev/null & DISPLAY=:0 termux-x11 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
echo ""
echo -e "Termux-x11 started"
echo ""
echo "Starting VirGL..."
MESA_NO_ERROR=1 virgl_test_server_android &
echo "VirGL started"

proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --bind $PREFIX/tmp/.X11-unix:/tmp/.X11-unix --bind $PREFIX/tmp/.virgl_test:/tmp/.virgl_test --no-sysvipc

pkill Xvfb
pkill -f "app_process / com.termux.x11"
