#!/bin/bash

unset LD_PRELOAD
export ROOTFSPATH=~/ubuntu
sudo mount -o remount,dev,suid /data
sudo mount proc -t proc $ROOTFSPATH/proc
sudo mount sys -t sysfs $ROOTFSPATH/sys
sudo mount --bind /dev $ROOTFSPATH/dev
sudo mount --bind /dev/pts $ROOTFSPATH/dev/pts
sudo mount --bind /sdcard $ROOTFSPATH/sdcard

echo " Starting Termux-x11..."
pkill Xvfb
pkill Xwayland
Xvfb -ac :0 &>/dev/null & DISPLAY=:0 termux-x11 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
clear
echo ""
echo -e "Termux-x11 started."

sudo ln $PREFIX/tmp/termux-x11 $ROOTFSPATH/tmp/termux-x11
sudo mount --bind $PREFIX/tmp/.X11-unix $ROOTFSPATH/tmp/.X11-unix
sudo chroot $ROOTFSPATH /bin/su -

sudo umount $ROOTFSPATH/proc
sudo umount $ROOTFSPATH/sys
sudo umount $ROOTFSPATH/dev/pts
sudo umount $ROOTFSPATH/dev
sudo umount $ROOTFSPATH/sdcard
sudo umount $ROOTFSPATH/tmp/.X11-unix
sudo rm $ROOTFSPATH/tmp/termux-x11
