#!/bin/sh

# The path of Ubuntu rootfs
UBUNTUPATH="/data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu"

# Fix setuid issue
sudo busybox mount -o remount,dev,suid /data

sudo busybox mount --bind /dev $UBUNTUPATH/dev
sudo busybox mount --bind /sys $UBUNTUPATH/sys
sudo busybox mount --bind /proc $UBUNTUPATH/proc
sudo busybox mount -t devpts devpts $UBUNTUPATH/dev/pts

# Mount sdcard
sudo busybox mount --bind /sdcard $UBUNTUPATH/sdcard
sudo busybox mount --bind /data/data/com.termux/files/tmp $UBUNTUPATH/tmp

# chroot into Ubuntu
sudo busybox chroot $UBUNTUPATH /bin/su - root

# Umount everything after exit
sudo busybox umount $UBUNTUPATH/dev/pts
sudo busybox umount $UBUNTUPATH/dev
sudo busybox umount $UBUNTUPATH/proc

# Original script can be found here: https://ivonblog.com/en-us/posts/termux-chroot-ubuntu/
