#!/bin/bash

echo " Starting Termux-x11..."
termux-x11 -nolisten tcp :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
echo ""
echo -e " Termux-x11 started"

proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --bind $PREFIX/tmp/.X11-unix:/tmp/.X11-unix

pkill -f "app_process / com.termux.x11"
