#!/bin/bash
clear
echo "You can find environment variables usage in"
echo "https://github.com/ptitSeb/box64/blob/main/docs/USAGE.md and"
echo "https://github.com/ptitSeb/box86/blob/master/docs/USAGE.md"
echo ""
echo "No need restart Box64Droid to apply changes"
echo ""
echo "Select environment variable to change:"
echo ""
echo "Box64"
echo "1) BOX64_DYNAREC_BIGBLOCK"
echo "2) BOX64_ALLOWMISSINGLIBS"
echo "3) BOX64_DYNAREC_STRONGMEM"
echo "4) BOX64_DYNAREC_X87DOUBLE"
echo "5) BOX64_DYNAREC_FASTNAN"
echo "6) BOX64_DYNAREC_FASTROUND"
echo "7) BOX64_DYNAREC_SAFEFLAGS"
echo "8) BOX64_DYNAREC_BLEEDING_EDGE"
echo "9) BOX64_DYNAREC_CALLRET"
echo ""
echo "Box86"
echo "10) BOX86_DYNAREC_BIGBLOCK"
echo "11) BOX86_ALLOWMISSINGLIBS"
echo "12) BOX86_DYNAREC_STRONGMEM"
echo "13) BOX86_DYNAREC_X87DOUBLE"
echo "14) BOX86_DYNAREC_FASTNAN"
echo "15) BOX86_DYNAREC_FASTROUND"
echo "16) BOX86_DYNAREC_SAFEFLAGS"
echo "17) BOX86_DYNAREC_BLEEDING_EDGE"
echo "18) BOX86_DYNAREC_CALLRET"
echo ""
echo "Misc"
echo "19) WINEESYNC (only for Wine 9.0-rc4)"
echo "20) Set to default all environment variables"
echo ""
echo "21) Back to previous menu"
echo ""
read envvar
if [ -z $envvar ]
then
	echo "Empty choice"
	. changeenvvars
elif [ $envvar = 1 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo "2) 2"
	echo "3) 3"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK/BOX64_DYNAREC_BIGBLOCK=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK/BOX64_DYNAREC_BIGBLOCK=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK/BOX64_DYNAREC_BIGBLOCK=2/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 3 ]
	then
		sed -i "s/BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK/BOX64_DYNAREC_BIGBLOCK=3/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK/BOX64_DYNAREC_BIGBLOCK=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 2 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_ALLOWMISSINGLIBS=$BOX64_ALLOWMISSINGLIBS/BOX64_ALLOWMISSINGLIBS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_ALLOWMISSINGLIBS=$BOX64_ALLOWMISSINGLIBS/BOX64_ALLOWMISSINGLIBS=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_ALLOWMISSINGLIBS=$BOX64_ALLOWMISSINGLIBS/BOX64_ALLOWMISSINGLIBS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 3 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo "2) 2"
	echo "3) 3"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_STRONGMEM=$BOX64_DYNAREC_STRONGMEM/BOX64_DYNAREC_STRONGMEM=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_STRONGMEM=$BOX64_DYNAREC_STRONGMEM/BOX64_DYNAREC_STRONGMEM=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX64_DYNAREC_STRONGMEM=$BOX64_DYNAREC_STRONGMEM/BOX64_DYNAREC_STRONGMEM=2/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 3 ]
	then
		sed -i "s/BOX64_DYNAREC_STRONGMEM=$BOX64_DYNAREC_STRONGMEM/BOX64_DYNAREC_STRONGMEM=3/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_STRONGMEM=$BOX64_DYNAREC_STRONGMEM/BOX64_DYNAREC_STRONGMEM=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 4 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_X87DOUBLE=$BOX64_DYNAREC_X87DOUBLE/BOX64_DYNAREC_X87DOUBLE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_X87DOUBLE=$BOX64_DYNAREC_X87DOUBLE/BOX64_DYNAREC_X87DOUBLE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_X87DOUBLE=$BOX64_DYNAREC_X87DOUBLE/BOX64_DYNAREC_X87DOUBLE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 5 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_FASTNAN=$BOX64_DYNAREC_FASTNAN/BOX64_DYNAREC_FASTNAN=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_FASTNAN=$BOX64_DYNAREC_FASTNAN/BOX64_DYNAREC_FASTNAN=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_FASTNAN=$BOX64_DYNAREC_FASTNAN/BOX64_DYNAREC_FASTNAN=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 6 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_FASTROUND=$BOX64_DYNAREC_FASTROUND/BOX64_DYNAREC_FASTROUND=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_FASTROUND=$BOX64_DYNAREC_FASTROUND/BOX64_DYNAREC_FASTROUND=0/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_FASTROUND=$BOX64_DYNAREC_FASTROUND/BOX64_DYNAREC_FASTROUND=1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 7 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo "2) 2"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_SAFEFLAGS=$BOX64_DYNAREC_SAFEFLAGS/BOX64_DYNAREC_SAFEFLAGS=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_SAFEFLAGS=$BOX64_DYNAREC_SAFEFLAGS/BOX64_DYNAREC_SAFEFLAGS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX64_DYNAREC_SAFEFLAGS=$BOX64_DYNAREC_SAFEFLAGS/BOX64_DYNAREC_SAFEFLAGS=2/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_SAFEFLAGS=$BOX64_DYNAREC_SAFEFLAGS/BOX64_DYNAREC_SAFEFLAGS/1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 8 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_BLEEDING_EDGE=$BOX64_DYNAREC_BLEEDING_EDGE/BOX64_DYNAREC_BLEEDING_EDGE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_BLEEDING_EDGE=$BOX64_DYNAREC_BLEEDING_EDGE/BOX64_DYNAREC_BLEEDING_EDGE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_BLEEDING_EDGE=$BOX64_DYNAREC_BLEEDING_EDGE/BOX64_DYNAREC_BLEEDING_EDGE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 9 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX64_DYNAREC_CALLRET=$BOX64_DYNAREC_CALLRET/BOX64_DYNAREC_CALLRET=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX64_DYNAREC_CALLRET=$BOX64_DYNAREC_CALLRET/BOX64_DYNAREC_CALLRET=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX64_DYNAREC_CALLRET=$BOX64_DYNAREC_CALLRET/BOX64_DYNAREC_CALLRET=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 10 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo "2) 2"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK/BOX86_DYNAREC_BIGBLOCK=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK/BOX86_DYNAREC_BIGBLOCK=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK/BOX86_DYNAREC_BIGBLOCK=2/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK/BOX86_DYNAREC_BIGBLOCK=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 11 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_ALLOWMISSINGLIBS=$BOX86_ALLOWMISSINGLIBS/BOX86_ALLOWMISSINGLIBS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_ALLOWMISSINGLIBS=$BOX86_ALLOWMISSINGLIBS/BOX86_ALLOWMISSINGLIBS=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_ALLOWMISSINGLIBS=$BOX86_ALLOWMISSINGLIBS/BOX86_ALLOWMISSINGLIBS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 12 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo "2) 2"
	echo "3) 3"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_STRONGMEM=$BOX86_DYNAREC_STRONGMEM/BOX86_DYNAREC_STRONGMEM=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_STRONGMEM=$BOX86_DYNAREC_STRONGMEM/BOX86_DYNAREC_STRONGMEM=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX86_DYNAREC_STRONGMEM=$BOX86_DYNAREC_STRONGMEM/BOX86_DYNAREC_STRONGMEM=2/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 3 ]
	then
		sed -i "s/BOX86_DYNAREC_STRONGMEM=$BOX86_DYNAREC_STRONGMEM/BOX86_DYNAREC_STRONGMEM=3/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_STRONGMEM=$BOX86_DYNAREC_STRONGMEM/BOX86_DYNAREC_STRONGMEM=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 13 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_X87DOUBLE=$BOX86_DYNAREC_X87DOUBLE/BOX86_DYNAREC_X87DOUBLE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_X87DOUBLE=$BOX86_DYNAREC_X87DOUBLE/BOX86_DYNAREC_X87DOUBLE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_X87DOUBLE=$BOX86_DYNAREC_X87DOUBLE/BOX86_DYNAREC_X87DOUBLE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 14 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_FASTNAN=$BOX86_DYNAREC_FASTNAN/BOX86_DYNAREC_FASTNAN=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_FASTNAN=$BOX86_DYNAREC_FASTNAN/BOX86_DYNAREC_FASTNAN=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_FASTNAN=$BOX86_DYNAREC_FASTNAN/BOX86_DYNAREC_FASTNAN=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 15 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_FASTROUND=$BOX86_DYNAREC_FASTROUND/BOX86_DYNAREC_FASTROUND=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_FASTROUND=$BOX86_DYNAREC_FASTROUND/BOX86_DYNAREC_FASTROUND=0/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_FASTROUND=$BOX86_DYNAREC_FASTROUND/BOX86_DYNAREC_FASTROUND=1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 16 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo "2) 2"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_SAFEFLAGS=$BOX86_DYNAREC_SAFEFLAGS/BOX86_DYNAREC_SAFEFLAGS=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_SAFEFLAGS=$BOX86_DYNAREC_SAFEFLAGS/BOX86_DYNAREC_SAFEFLAGS=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 2 ]
	then
		sed -i "s/BOX86_DYNAREC_SAFEFLAGS=$BOX86_DYNAREC_SAFEFLAGS/BOX86_DYNAREC_SAFEFLAGS=2/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_SAFEFLAGS=$BOX86_DYNAREC_SAFEFLAGS/BOX86_DYNAREC_SAFEFLAGS/1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 17 ]
then
	clear
	echo "Select vaule (empty or another = default (1)):"
	echo "1) 0"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_BLEEDING_EDGE=$BOX86_DYNAREC_BLEEDING_EDGE/BOX86_DYNAREC_BLEEDING_EDGE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_BLEEDING_EDGE=$BOX86_DYNAREC_BLEEDING_EDGE/BOX86_DYNAREC_BLEEDING_EDGE=0/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_BLEEDING_EDGE=$BOX86_DYNAREC_BLEEDING_EDGE/BOX86_DYNAREC_BLEEDING_EDGE=1/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 18 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/BOX86_DYNAREC_CALLRET=$BOX86_DYNAREC_CALLRET/BOX86_DYNAREC_CALLRET=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/BOX86_DYNAREC_CALLRET=$BOX86_DYNAREC_CALLRET/BOX86_DYNAREC_CALLRET=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/BOX86_DYNAREC_CALLRET=$BOX86_DYNAREC_CALLRET/BOX86_DYNAREC_CALLRET=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 19 ]
then
	clear
	echo "Select vaule (empty or another = default (0)):"
	echo "1) 1"
	echo ""
	read envvar
	if [ -z $envvar ]
	then
		sed -i "s/WINEESYNC=$WINEESYNC/WINEESYNC=0/g" /sdcard/Box64Droid/Box64Droid.conf
	elif [ $envvar = 1 ]
	then
		sed -i "s/WINEESYNC=$WINEESYNC/WINEESYNC=1/g" /sdcard/Box64Droid/Box64Droid.conf
	else
		sed -i "s/WINEESYNC=$WINEESYNC/WINEESYNC=0/g" /sdcard/Box64Droid/Box64Droid.conf
	fi
	. /sdcard/Box64Droid/Box64Droid.conf
	. changeenvvars
elif [ $envvar = 20 ]
then
	cp $PREFIX/glibc/opt/Box64Droid.conf /sdcard/Box64Droid/
	. changeenvvars
elif [ $envvar = 21 ]
then
	. start-box64
else
	echo "Wrong choice"
	. changeenvvars
fi
