#!/bin/bash
clear
echo " Starting Box64Droid (native version) installation..." & sleep 3
echo ""
echo " Box64Droid creates /sdcard/Box64Droid folder to store configuration files. To create this folder, it is necessary to have storage permissions, click on allow to proceed." & sleep 5 &>/dev/null
termux-setup-storage & sleep 3 &>/dev/null
echo ""
echo " Updating packages..."
apt-get update &>/dev/null
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade &>/dev/null
echo ""
echo " Installing x11-repo..."
echo ""
pkg install x11-repo -y &>/dev/null
echo " x11-repo installed"
echo ""
echo " Installing required packages..."
pkg install pulseaudio wget xkeyboard-config freetype fontconfig libpng xorg-xrandr termux-x11-nightly termux-am -y &>/dev/null
echo ""
echo " Checking for older Box64Droid versions and removing them if any..."
echo ""
if [ -d ~/.wine ]
then
  rm -r ~/.wine &>/dev/null
  rm -r $PREFIX/glibc &>/dev/null
fi
if [ -d /sdcard/Box64Droid ]
then
  rm -r /sdcard/Box64Droid &>/dev/null
fiAIMP (on Wine)
echo " Downloading glibc prefix..."
echo ""
wget -q --show-progress https://github.com/Ilya114/Box64Droid/releases/download/alpha/glibc-prefix.tar.xz
echo ""
echo " Unpacking glibc-prefix, please wait..."
tar -xJf glibc-prefix.tar.xz -C $PREFIX/
echo ""
echo " Downloading Box64Droid starting scripts..."
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/native/box64droid &>/dev/null
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/native/start-box64 &>/dev/null
wget https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/native/changeenvvars &>/dev/null
chmod +x box64droid start-box64 changeenvvars
mv box64droid start-box64 changeenvvars $PREFIX/bin/
echo ""
echo " Scripts downloaded"
echo ""
echo " Removing the installation waste..."
rm glibc-prefix.tar.xz install native
clear
echo ""
echo " Install finished. To start Box64Droid run 'box64droid --start', to see more arguments run 'box64droid --help'"
echo ""
echo " And if everything goes as planned, Wine and 7-Zip file manager will start."
echo ""
